@startuml

interface Attackable {
    + {abstract} void attack()
}

interface Runnable {
    + {abstract} void run()
}

abstract class Character implements Attackable, Runnable {
    + int hp;
    + String name;
}

@enduml 