@startuml
scale 2

interface Attackable {
    + {abstract} void attack()
}

interface Runnable {
    + {abstract} void run()
}

class Dog implements Runnable {
}


abstract class Character implements Attackable, Runnable {
+ int hp;
+ String name;
}

abstract class Monster extends Character {
 + void run()
}
class Goblin extends Monster {
}
@enduml