@startuml

scale 2

class Hero {
{static} int Money
    +String name
    +int hp

    +void attack(Slime slime)
    +void run()
'    +attack()
'    -die()
}

class Cleric{
}

class Wizard{
}

class SuperHero extends Hero {
    +bool isFlying
}
@enduml