name: learn_dart_together
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  csv: ^6.0.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  xml: ^6.5.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0