name: learn_dart_together
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  csv: ^6.0.0
  intl: ^0.19.0
  xml_parser: ^1.0.0
  http: ^0.13.6
  dio: ^5.4.3+1
  xml: ^6.5.0
  xml2json: ^6.2.3
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  freezed_annotation: ^2.1.1
  shelf_web_socket: ^2.0.0
  flutter_dotenv: ^5.1.0
  # path: ^1.8.0

dependency_overrides:
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
  analyzer: ^6.5.0


