@startuml

interface Attackable {
+{abstract} void attack()
}

abstract class Character implements Attackable{
+ {abstract}void attack()
+ {abstract}void run()
}

abstract class Monster extends Character{
+void run()
}

class Goblin extends Monster {

}
@enduml