@startuml book

class Book {
  + title: String
  + author: String
  + genre: String
}

class Fiction {
  + subgenre: String
}

class NonFiction {
  + subject: String
}

Book <|-- Fiction
Book <|-- NonFiction

@enduml
