@startuml
class Animal {
    + String type
    + String sound
    + void eat()
    + void makeSound()
}

class Dog extends Animal {
    + bool hasSpots
    + String color
    + void makeSound() @override
    + void wagTail()
}

class Cat extends Animal {
    + bool hasSpots
    + String color
    + void scratch()
}

class Bird extends Animal {
    + bool hasSpots
    + String beakColor
    + String color
    + void fly()
}

@enduml